add search forreal!
lbialik/bolete-filter-app pull request #12
Opened 2021-02-08 22:00 UTC by lbialik

2021-02-08 22:06 UTC, JackKenney requested changes
Saw a couple things that could be cleaner

2021-02-08 22:06 UTC, JackKenney commented on src/screens/MainScreen.tsx
> +      return data[speciesID]["Name"].toLowerCase().includes(text) | data[speciesID]["Common Name"].toLowerCase().includes(text) | data[speciesID]["SKU"].toLowerCase().includes(text)
can extract `data[speciesID]` into `const` variable to improve readability

2021-02-08 22:06 UTC, JackKenney commented on src/screens/MainScreen.tsx
> +      species = this.filterSpecies(search.toLowerCase());
might want to move `search.toLowerCase()` into the `filterSpecies` method / the `qualifies` function because those depend on it being lowercase and could be used elsewhere and not work properly since they don't do the lower-casing themselves.

2021-02-08 22:06 UTC, JackKenney commented on src/screens/MainScreen.tsx
> +    // item"name"], item["common name"], item["SKU"]
delete printouts

2021-02-09 03:53 UTC, lbialik commented on src/screens/MainScreen.tsx
> +      return data[speciesID]["Name"].toLowerCase().includes(text) | data[speciesID]["Common Name"].toLowerCase().includes(text) | data[speciesID]["SKU"].toLowerCase().includes(text)
:+1:

2021-02-09 04:09 UTC, lbialik commented on src/screens/MainScreen.tsx
> +      species = this.filterSpecies(search.toLowerCase());
:+1:

2021-02-09 04:09 UTC, lbialik commented on src/screens/MainScreen.tsx
> +    // item"name"], item["common name"], item["SKU"]
:+1:

2021-02-09 04:12 UTC, merged